name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
       sudo add-apt-repository multiverse
       sudo dpkg --add-architecture i386
       sudo apt update
       sudo apt install lib32gcc1 steamcmd
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
